spring.application.name=rate-limiter-registration-service

spring.datasource.url=jdbc:postgresql://localhost:5432/distributed-rate-limiter
spring.datasource.username=postgres
spring.datasource.password=wb02z3125
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update


# External Eureka Server URL
eureka.client.service-url.defaultZone=http://localhost:9000/eureka/